#! /bin/bash


function discoLibre () {
    if [ $# -eq 0 ]; then
        discoLibre `df -h /var | tail -n1 `
    else
        echo -n "$4"
    fi
}


function detalleDisco () {
    if [ $# -eq 0 ]; then
        detalleDisco `df -h /var | tail -n1 `
    else
        echo -n "Cap: $2 - Uso: $3 ($5) - Libre: $4"
    fi
}

function getMyIp () {
    if [ `whereis ifconfig | wc -w` -gt 1 ]; then
	echo `/sbin/ifconfig | grep "Bcast:" | egrep -o '\b[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\b' | sed s/\\n//g | sed s/\\r//g`
    else
	echo -n `ipconfig.exe | grep "Direcci" | egrep -o '\b[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\b' | sed s/\\n//g | sed s/\\r//g`
    fi
}

function getTunelPort () {
    if [ -f /usr/local/dokkoTunel/dokkoTunel.conf ]; then
        . /usr/local/dokkoTunel/dokkoTunel.conf
	echo "$serverPort"
    else
        echo "none"
    fi
}

url=http://monitor.dokkogroup.com.ar/monitor.php
dmversion=0.5

cd `dirname $0`

if [ -f monitor.conf ]; then
    . monitor.conf
else
    echo "Cant params: "$#
    if [ $# -ne 5 ]; then
        echo "Param1 = Nombre, Param2 = Estado, Param3 = Id categoria, Param4 = Tiempo envio info, Param5 = Version del dokko monitor"
        exit;
    fi
    nombre=$1
    estado=$2
    categoria=$3
    tiempo_envio=$4
    dmversion=$5
fi

myIp=`getMyIp`
tunel=`getTunelPort`
kernel=`uname -r`
capDisco=`discoLibre`
detalleDisco=`detalleDisco`
fecha=`date "+%Y-%m-%d %H:%M:%S"`
nombreRed=`uname -n`
uptime=`uptime | sed s/\\n//g | sed s/\\r//g`
params="nombre=$nombre&nombreRed=$nombreRed&estado=$estado&categoria=$categoria&disco_libre_mb=$capDisco&kernel=$kernel&fecha=$fecha&detalleDisco=$detalleDisco&uptime=$uptime&version_dm=$dmversion&tiempo_envio=$tiempo_envio&tunel=$tunel&myIp=$myIp"

function lynxConTimeout() {
    lynx --source -connect_timeout=25 "$1" &
    lynxId=$!
    
    for((i=0;i<60;i++)); do
        sleep 1
        rta=`ps -p $lynxId | grep $lynxId`
        if [ "$rta" == "" ]; then
            return 0
        fi
	if [ $i -eq 25 ]; then
	    echo -n "Pasaron 25 segundos, faltan 35 para abortar el proceso: " 1>&2
	fi
	if [ $i -gt 25 ]; then
	    echo -n "." 1>&2
	fi
    done

    kill -KILL $lynxId
    echo " Timeout " 1>&2
    return 1
}

if respuesta=`lynxConTimeout "$url?$params"` ; then
    ./ejecutarAccion $respuesta
else
    echo "Timeout esperando a Lynx... se mato el proceso"
fi
